name: mozzarellm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - tqdm
  - pip
  - ipykernel
  - pytest
  - openpyxl
  - matplotlib
  - pip:
      - openai>=1.70.0
      - python-dotenv>=1.0.0
      - google-genai>=1.9.0
      - anthropic>=0.49.0
      - requests>=2.31.0