name: mozzarellm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - tqdm
  - pip
  - ipykernel
  - pytest
  - pip:
      - openai
      - python-dotenv
      - google-genai
      - anthropic
      - requests