name: mozzarellm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - numpy=1.24.4
  - tqdm>=4.66.3
  - pip
  - ipykernel
  - pytest
  - pip:
      - openai
      - python-dotenv==1.0.0
      - google-genai
      - anthropic
      - requests>=2.32.0
      - logging==0.4.9.6